<?php
/*
Copyright (c) 2012-2013 Jon Plaut

* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.

* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/

/*
* To do: 
* Set variables in a more memory-effiecient way (bulk set instead of individual)
*/

require_once("google-api-php-client/apiClient.php");
require_once("google-api-php-client/contrib/apiAnalyticsService.php");

define("SCOPE", "https://www.googleapis.com/auth/analytics.readonly");

/*
* Object that takes an unauthenticated ApiClient and returns either a
* fully authenticated client or Null if no authentication has been requested 
*/

class AuthenticatedClient {
	public $unauthenticatedClient;
	public $service;
	public $client;
	
	public function __construct() {
		$this->unauthenticatedClient = new apiClient();
		$this->service = new apiAnalyticsService($this->unauthenticatedClient);
		$this->client = Null;
		
		if (!variable_get("googleApiAccessToken", "") || !variable_get("googleApiRefreshToken", "")) {
			if ($_GET['code']) {
				// If there is no access token or refresh token and client is returned
				// to the config page with an access code, complete the authentication
				self::full_auth();
			}
		} else {
			if (time() > variable_get("googleApiTokenExpires", "")) {
				// If the site has an access token and refresh token, but the
				// refresh token has expired, authenticate the user with the
				// refresh token
				self::refresh_token();
			} else {
				// If the access token is still valid, authenticate the user with that
				self::access_token();
			}
		}
		
		return $this->client;
	}
	
	/*
	* Authenticates a client using a valid refresh token and saves the variables
	* to the database. Returns authenticated client, or Null if unsuccessful.
	*/
	protected function refresh_token() {
		$this->unauthenticatedClient -> setClientId(variable_get("googleApiClientId", ""));
		$this->unauthenticatedClient -> setClientSecret(variable_get("googleApiClientSecret", ""));
		$this->unauthenticatedClient -> refreshToken(variable_get('googleApiRefreshToken', ""));
		
		try{
			$this->client = $this->unauthenticatedClient;
			self::set_google_api_variables();
		}
		catch (Exception $e) {
			drupal_set_message(t("Authentication failed. Please check Client ID and Client Secret."), 'error', false);
			$this->client = Null;
		}
	}
	
	/*
	* Authenticates a client using Client ID and Client Secret and saves the variables
	* to the database. Returns authenticated client, or Null if unsuccessful.
	*/
	protected function full_auth() {
		drupal_get_messages();
		
		$this->unauthenticatedClient -> setClientId(variable_get("googleApiClientId", ""));
		$this->unauthenticatedClient -> setClientSecret(variable_get("googleApiClientSecret", ""));
		$this->unauthenticatedClient -> setRedirectUri(get_current_url());
		$this->unauthenticatedClient -> setScopes(SCOPE);
		
		try{
			$this->unauthenticatedClient -> authenticate();
			$this->client = $this->unauthenticatedClient;
			self::set_google_api_variables();
			drupal_set_message(t("Authentication successful."));
		}
		catch (Exception $e) {
			drupal_set_message(t("Authentication failed. Please check Client ID and Client Secret."), 'error', false);
			$this->client = Null;
		}
	}
	
	/*
	* Authenticates a client using a valid access token and returns authenticated client, 
	* or Null if unsuccessful.
	*/
	protected function access_token() {
		try {
			$this->unauthenticatedClient -> setAccessToken(variable_get("googleApiFullResponse", ""));
			$this->client = $this->unauthenticatedClient;
		}
		catch (Exception $e) {
			drupal_set_message(t("Authentication failed. Please check Client ID and Client Secret."), 'error', false);
			$this->client = Null;
		}
	}
	
	/*
	* Authenticates a client using Client ID and Client Secret and saves the variables
	* to the database. Returns authenticated client, or Null if unsuccessful.
	*/
	public function get_auth_url() {
		$this->unauthenticatedClient -> setClientId(variable_get("googleApiClientId", ""));
		$this->unauthenticatedClient -> setClientSecret(variable_get("googleApiClientSecret", ""));
		$this->unauthenticatedClient -> setRedirectUri(get_current_url());
		$this->unauthenticatedClient -> setScopes(SCOPE);
	
		$authUrl = $this->unauthenticatedClient -> createAuthUrl();
		
		return $authUrl;
	}
	
	/*
	* Save returned access token to database
	*/
	protected function set_google_api_variables() {
		$tokenJSON = json_decode($this->client -> getAccessToken(), true);
		
		variable_set("googleApiFullResponse", $this->client -> getAccessToken());
		variable_set("googleApiAccessToken", $tokenJSON['access_token']);
		variable_set("googleApiTokenExpires", $tokenJSON['created'] + $tokenJSON['expires_in']);
		
		if ($tokenJSON['refresh_token']) {
			variable_set("googleApiRefreshToken", $tokenJSON['refresh_token']);
		}
	}
	
	public function is_authenticated() {
		return ($this->client) ? true : false;
	}
}

/*
* Object that takes an AuthenticatedClient and returns a form array
*/
class GoogleConfigForm {
	public $client;
	private $isAuthenticated;
	
	public function __construct($client) {
		$this->client = $client;
		$this->isAuthenticated = $this->client -> is_authenticated();
	}
	
	public function make_form() {
		// Add standard form elements
		$form['googleApiClientId'] = array(
			'#type' => 'textfield',
			'#title' => t('Client ID'),
			'#default_value' => variable_get('googleApiClientId', ''),
			'#size' => 30,
			'#description' => t('Client ID created for the app in the access tab of the ') . l('Google API Console', 'http://code.google.com/apis/console', array('attributes' => array('target' => '_blank'))),
		);

		$form['googleApiClientSecret'] = array(
			'#type' => 'textfield',
			'#title' => t('Client Secret'),
			'#default_value' => variable_get('googleApiClientSecret', ''),
			'#size' => 30,
			'#description' => t('Client Secret created for the app in the Google API Console'),
		);

		if ($this->isAuthenticated) {
			try{
				// If authentication was successful, try to get list of profiles
				$profiles = self::get_profiles($this->client->service);

				$form['googleAnalyticsProfile'] = array(
					'#type' => 'select',
					'#title' => 'Select a profile: ',
					'#description' => t('Google Analytics profile for this site.'),
					'#options' => $profiles,
					'#default_value' => variable_get('googleAnalyticsProfile', ""),
				);
			}
			catch (Exception $e) {
				// If unable to get profiles, throw an error
				$this->isAuthenticated = false;
				delete_googleAPI_vars();
				drupal_get_messages();
				drupal_set_message(t("Could not retrieve profiles. Please make sure you are logged into the correct Google account and try authenticating again."), 'error', false);
			}
		}

		if (!$this->isAuthenticated) {
			// If site is not authenticated, add standard submit buttons
			$form['auth'] = array(
				'#type' => 'submit',
				'#value' => 'Authenticate',
				'#submit' => array('googleAPI_config_auth'),
			);
		} else {	
			// If site is authenticated, add Deauthenticate and Save buttons
			$form['save'] = array(
				'#type' => 'submit',
				'#value' => 'Save',
				'#submit' => array('googleAPI_config_save'),
			);
			$form['deauth'] = array(
				'#type' => 'submit',
				'#value' => 'Deauthenticate',
				'#validate' => array(),
				'#submit' => array('googleAPI_config_deauth'),
			);
		}
	
		return $form;
	}
	
	/*
	* Query Google for Analytics profiles and formats them for use in 
	* config form
	*/
	protected function get_profiles($service) {
		$profiles = $service->management_profiles->listManagementProfiles("~all", "~all", array('fields' => "items(id,name)"));
		$profileList = array();
		foreach ($profiles['items'] as $profile) {
			$profileList[$profile['id']] = $profile['name'];
		}
		return $profileList;
	}
}

/*
* Returns current URL
*/
function get_current_url() {
	$s = empty($_SERVER["HTTPS"]) ? '' : ($_SERVER["HTTPS"] == "on") ? "s" : "";
	$protocol = substr(strtolower($_SERVER["SERVER_PROTOCOL"]), 0, strpos(strtolower($_SERVER["SERVER_PROTOCOL"]), "/")) . $s;
	$port = ($_SERVER["SERVER_PORT"] == 80) ? "" : (":" . $_SERVER["SERVER_PORT"]);
	$requestURI = explode("?", $_SERVER["REQUEST_URI"]);
	return $protocol . "://" . $_SERVER["SERVER_NAME"] . $port . $requestURI[0];
}

/*
* Deletes all GoogleAPI variables set during configuration
*/
function delete_googleAPI_vars() {
	variable_del("googleApiClientId");
	variable_del("googleApiClientSecret");
	variable_del("googleApiAccessToken");
	variable_del("googleApiRefreshToken");
	variable_del("googleApiTokenExpire");
	variable_del("googleApiFullResponse");
	variable_del("googleAnalyticsProfile");
}

/*
* Implements hook_help
*/
function googleAPI_help($path, $arg) {
	$output = '';
	
	switch($path) {
		case "admin/help#googleAPI":
			$output = '<p>' . t("Helps integrate Drupal sites with the Google API.");
			break;
	}
	return $output;
}

/*
* GoogleAPI configuration page
*/
function googleAPI_config($form) {
	$client = new AuthenticatedClient($unauthenticatedClient);
	
	$form = new GoogleConfigForm($client);
	$form = $form -> make_form();
	
	return $form;
}

/*
* Validate the configuration form. If Client ID or Client Secret
* are not filled in, throw an error.
*/
function googleAPI_config_validate($form, &$form_state) {
	if (!$form_state['values']['googleApiClientId'] || !$form_state['values']['googleApiClientSecret']) {
		form_set_error('', t('You must enter a valid client ID and client Secret.'));
	}
}

/*
* Begins authentication process. 
* Performed when the first time the user requests authentication
*/
function googleAPI_config_auth($form, &$form_state) {
	// If there are any lingering error messages, clear them
	drupal_get_messages();
	
	variable_set("googleApiClientId", $form_state['values']['googleApiClientId']);
	variable_set("googleApiClientSecret", $form_state['values']['googleApiClientSecret']);
	
	$authURL = new AuthenticatedClient();
	$authURL = $authURL -> get_auth_url();

	header("Location: " . $authURL);
	
	echo "Error.";
}

/*
* Unsets all googleApi variables.
* Performed when a user hits "Deauthenticate" on the config page
*/ 
function googleAPI_config_deauth($form, &$form_state) {
	drupal_get_messages();
	delete_googleAPI_vars();
	drupal_set_message("Site successfully deauthenticated.");
}

/*
* Saves googleApi config settings.
* Performed when user is authenticated and hits "Save" on the config form
*/
function googleAPI_config_save($form, &$form_state) {
	// If there are any lingering error messages, clear them
	drupal_get_messages();
	
	if ($form_state['values']['googleApiClientId'] != variable_get("googleApiClientId", "") || $form_state['values']['googleApiClientSecret'] != variable_get("googleApiClientSecret", "")) {
		delete_googleAPI_vars();
		variable_set("googleApiClientId", $form_state['values']['googleApiClientId']);
		variable_set("googleApiClientSecret", $form_state['values']['googleApiClientSecret']);
		googleAPI_config_auth($form, $form_state);
	} else {
		variable_set("googleAnalyticsProfile", $form_state['values']['googleAnalyticsProfile']);
		drupal_set_message("Settings saved.");
	}
}

/*
* Implements hook_menu
*/
function googleAPI_menu() {
	$items = array();
	
	$items['siteAnalytics'] = array(
		'title' => 'Site Analytics',
		'page callback' => 'googleAPI_all',
		'access arguments' => array('access googleAPI content'),
		'weight' => 9,
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['admin/settings/googleAPI'] = array(
		'title' => t('Google API Settings'),
		'description' => t('Google API configuration page'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('googleAPI_config'),
		'access arguments' => array('access googleAPI content'),
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}

/*
* Called when user accesses the "Site Analytics" page.
* Displays Google Analytics data.
*/
function googleAPI_all() {
	$output = "";
	
	if (variable_get('googleApiAccessToken', '')) {
		$client = new AuthenticatedClient();

		if ($client->is_authenticated()) {
			try {
				//If authentication was successful, display Google Analytics data
				$data = $client->service->data_ga -> get(
					'ga:' . variable_get("googleAnalyticsProfile", ""),
					'2005-01-01',
					date('Y-m-d'),
					'ga:visits,ga:pageviews',
					array(
						'fields' => 'totalsForAllResults',
					)
				);
				foreach ($data as $elem) {
					$output .= "<li>Visits: " . $elem['ga:visits'] . "</li><li>Page Views: " . $elem['ga:pageviews'] . "</li>";
				}
			}
			catch (Exception $e) {
				// If unable to get data, throw an error.
				$output .= "<p>Unable to get data from Google. Please " . l('reconfigure Google API', 'admin/settings/googleAPI') . ".</p>";
			}	
		}
	} else {
			// If user is not authenticated, send user to GoogleAPI config page
			$output .= "<p>Please " . l('configure Google API', 'admin/settings/googleAPI') . ".</p>";
	}
	
	return $output;
}